### ISSUE TITLE
What is the purpose of tail identifier array in .client files?

### ISSUE THREAD

**Issue by anoopemacs** [tomzx/ofocus-format#5]
Lets say omnifocus v2 from Mac is synced up to the below master file on some WebDAV:
000={A}+{B}.zip
mac.client **( tail identifier = B )**

Now omnifocus from iphone adds the below transaction files to the webdav:
{GMT}={B}+{C}.zip
iphone.client **( tail identifier = C )**

Now, we press sync in Omnifocus Mac, how does it know what transaction files to get from .ofocus in webdav?
My Guess: Since mac.client tail identifier was B earlier, it knows to get the B+something zip file

---

However the above guess is wrong because:

000={A}+{B}.zip
mac.client **( tail identifier = B )**

Now omnifocus from iphone adds the below transaction files to the webdav:
{GMT}={B}+{C}.zip
iphone.client **( tail identifier = C )**

Now manually edit the tail identifier in the mac.client file to 'C'

Therefore, present state of webdav server is:
000={A}+{B}.zip
mac.client **( tail identifier = C )**
{GMT}={B}+{C}.zip
iphone.client **( tail identifier = C )**

Now press sync in Omnifocus Mac, even now it get the B+C task we added from iphone to Mac

---

So, when is the tail identifier array ever used?

**Comment by tomzx** [comment]
The tail identifier is most likely used by the updating clients. If all `*.client` files are synced up to a point (let's say C), it can then compress all the previous transactions files into the master file (effectively containing A-C instead of A-B).

When a client updates with Webdav, it will check the last tail identifier available locally, not remotely/on webdav. It then uses that to determine what to fetch.

Thus, in your example, what would possibly happen is that if you were to do another update with the iPhone (let's call it C-D), then the master/A-B file would likely disappear and be turned into A-C. When the Mac client would connect to Webdav, it would be unable to find B-anything and thus ask the user to either keep its local db or sync the remote db completely.

**Comment by anoopemacs** [comment]
> When the client updates with webdav, it will check the last tail identifier available locally, not remotely/on webdav

By locally do you mean, on Mac it will check in /Users/username/Library/Containers/com.omnigroup.OmniFocus2/Data/Library/Application Support/OmniFocus/OmniFocus.ofocus

**Comment by tomzx** [comment]
Yes. If you open this file (Show Package Contents), you will see all the zip files explained in the README.md.

**Comment by anoopemacs** [comment]
Thank you, I tested out the above example and your guess is actually what happened.
It asked to either keep its local db or sync the remote db completely.
